/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { BookingService } from "../booking.service";
import { BookingCreateInput } from "./BookingCreateInput";
import { Booking } from "./Booking";
import { BookingFindManyArgs } from "./BookingFindManyArgs";
import { BookingWhereUniqueInput } from "./BookingWhereUniqueInput";
import { BookingUpdateInput } from "./BookingUpdateInput";
import { PassengerListFindManyArgs } from "../../passengerList/base/PassengerListFindManyArgs";
import { PassengerList } from "../../passengerList/base/PassengerList";
import { PassengerListWhereUniqueInput } from "../../passengerList/base/PassengerListWhereUniqueInput";

export class BookingControllerBase {
  constructor(protected readonly service: BookingService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Booking })
  async createBooking(
    @common.Body() data: BookingCreateInput
  ): Promise<Booking> {
    return await this.service.createBooking({
      data: {
        ...data,

        fleet: data.fleet
          ? {
              connect: data.fleet,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        bookingDate: true,
        createdAt: true,

        fleet: {
          select: {
            id: true,
          },
        },

        id: true,
        numberOfPassengers: true,
        status: true,
        travelDate: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Booking] })
  @ApiNestedQuery(BookingFindManyArgs)
  async bookings(@common.Req() request: Request): Promise<Booking[]> {
    const args = plainToClass(BookingFindManyArgs, request.query);
    return this.service.bookings({
      ...args,
      select: {
        bookingDate: true,
        createdAt: true,

        fleet: {
          select: {
            id: true,
          },
        },

        id: true,
        numberOfPassengers: true,
        status: true,
        travelDate: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Booking })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async booking(
    @common.Param() params: BookingWhereUniqueInput
  ): Promise<Booking | null> {
    const result = await this.service.booking({
      where: params,
      select: {
        bookingDate: true,
        createdAt: true,

        fleet: {
          select: {
            id: true,
          },
        },

        id: true,
        numberOfPassengers: true,
        status: true,
        travelDate: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Booking })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateBooking(
    @common.Param() params: BookingWhereUniqueInput,
    @common.Body() data: BookingUpdateInput
  ): Promise<Booking | null> {
    try {
      return await this.service.updateBooking({
        where: params,
        data: {
          ...data,

          fleet: data.fleet
            ? {
                connect: data.fleet,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          bookingDate: true,
          createdAt: true,

          fleet: {
            select: {
              id: true,
            },
          },

          id: true,
          numberOfPassengers: true,
          status: true,
          travelDate: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Booking })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteBooking(
    @common.Param() params: BookingWhereUniqueInput
  ): Promise<Booking | null> {
    try {
      return await this.service.deleteBooking({
        where: params,
        select: {
          bookingDate: true,
          createdAt: true,

          fleet: {
            select: {
              id: true,
            },
          },

          id: true,
          numberOfPassengers: true,
          status: true,
          travelDate: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/passengerLists")
  @ApiNestedQuery(PassengerListFindManyArgs)
  async findPassengerLists(
    @common.Req() request: Request,
    @common.Param() params: BookingWhereUniqueInput
  ): Promise<PassengerList[]> {
    const query = plainToClass(PassengerListFindManyArgs, request.query);
    const results = await this.service.findPassengerLists(params.id, {
      ...query,
      select: {
        booking: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        ferry: true,
        id: true,
        passengerEmail: true,
        passengerName: true,
        travelDate: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/passengerLists")
  async connectPassengerLists(
    @common.Param() params: BookingWhereUniqueInput,
    @common.Body() body: PassengerListWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      passengerLists: {
        connect: body,
      },
    };
    await this.service.updateBooking({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/passengerLists")
  async updatePassengerLists(
    @common.Param() params: BookingWhereUniqueInput,
    @common.Body() body: PassengerListWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      passengerLists: {
        set: body,
      },
    };
    await this.service.updateBooking({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/passengerLists")
  async disconnectPassengerLists(
    @common.Param() params: BookingWhereUniqueInput,
    @common.Body() body: PassengerListWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      passengerLists: {
        disconnect: body,
      },
    };
    await this.service.updateBooking({
      where: params,
      data,
      select: { id: true },
    });
  }
}
